version: "3"

services:
  gschwa:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./www:/usr/local/src/gschwa:ro"
      - "./data/nginx:/etc/nginx/conf.d:ro"
      - "./data/certbot/conf:/etc/letsencrypt:ro"
      - "./data/certbot/www:/var/www/certbot:ro"

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
